### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ben-dev2609** [MRHRTZ/DGC-ChatBotV3#2]
C:\Users\User\DGC-ChatBotV3\node_modules\sharp\lib\constructor.js:34
  throw new Error(error);
  ^

Error:
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp.node'
Require stack:
- C:\Users\User\DGC-ChatBotV3\node_modules\sharp\lib\constructor.js
- C:\Users\User\DGC-ChatBotV3\node_modules\sharp\lib\index.js
- C:\Users\User\DGC-ChatBotV3\node_modules\@open-wa\wa-automate\dist\api\Client.js
- C:\Users\User\DGC-ChatBotV3\node_modules\@open-wa\wa-automate\dist\index.js
- C:\Users\User\DGC-ChatBotV3\index.js

- Run "npm rebuild --verbose sharp" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/install
- Search for this error at https://github.com/lovell/sharp/issues

    at Object.<anonymous> (C:\Users\User\DGC-ChatBotV3\node_modules\sharp\lib\constructor.js:34:9)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
    at Object.<anonymous> (C:\Users\User\DGC-ChatBotV3\node_modules\sharp\lib\index.js:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
npm ERR! code 1
npm ERR! path C:\Users\User\DGC-ChatBotV3
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c "node index.js"

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2020-11-03T10_29_56_549Z-debug.log****

**Comment by MRHRTZ** [comment]
On sharp issue install <a href=https://github.com/lovell/sharp/issues/1696>See #1696</a>

The error isn't from this repo, its from sharp see that issue and closing for now thanks
